@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package nowebsite.makertechno.lights_up.common.init;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;